version: '3'

services:
  tts-ru:
    image: registry.mix.local/mixer/tts-server
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    environment:
      # - TTS_MODEL=path to another model
      - SPEAKER=kseniya
    ports:
      - "2800:8000"